### ISSUE TITLE
ransackで検索機能の実装（地図一覧）

### ISSUE THREAD

**Issue by nakayama-bird** [nakayama-bird/metime-meals#29]
#### コントローラ
- [ ] indexアクションについてransack導入に伴い変更
#### ビューファイル
- [ ] 検索欄の実装(投稿内容、タグ、来店時間、金額)
- [ ] 検索欄をタブで出せるようにする
- [ ] 検索内容のクリアボタン
- [ ] パーシャル表示箇所についてransack導入に伴い変更
### ゴール
- 投稿の検索ができるようになる
### 参考資料
- [Rails基礎18](https://school.runteq.jp/v3/curriculums/rails_basic/chapters/18)
### 注意点
- 検索項目が多いので投稿内容、タグを優先的に実装

**Comment by nakayama-bird** [comment]
### 関連するissue
https://github.com/nakayama-bird/metime-meals/issues/22
### 追加
投稿一覧で投稿がない場合の条件分岐も一緒に設定する。

**Comment by nakayama-bird** [comment]
## 実装の流れ
- Postコントローラと同じように実装したら検索するとカードの一覧に遷移するようになってしまった
- Formオブジェクトなので検索フォーム自体はそのまま使用できるはず
- ルーティングが怪しい？
### ルーティング
- 設定する
```
  resources :maps, only: %i[index] do
    collection do
      get :search
    end
  end
```
- search_maps_pathに変更する
```
search_maps GET    /maps/search(.:format)                                                                            maps#search
```

**Comment by nakayama-bird** [comment]
## 実装の流れ（エラー内容：undefined method `search' for nil:NilClass)
-上記の実装をした後下記エラー
```
Started GET "/maps/search?q%5Baddress_or_name%5D=&q%5Bgenre_select%5D=western_food&commit=%E6%A4%9C%E7%B4%A2" for 192.168.65.1 at 2024-08-23 18:35:54 +0900
web-1  | 18:35:54 web.1  | Cannot render console from 192.168.65.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web-1  | 18:35:54 web.1  | Processing by MapsController#search as HTML
web-1  | 18:35:54 web.1  |   Parameters: {"q"=>{"address_or_name"=>"", "genre_select"=>"western_food"}, "commit"=>"検索"}
web-1  | 18:35:54 web.1  | Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms | Allocations: 900)
web-1  | 18:35:54 web.1  | 
web-1  | 18:35:54 web.1  | 
web-1  | 18:35:54 web.1  |   
web-1  | 18:35:54 web.1  | NoMethodError (undefined method `search' for nil:NilClass):
```

**Comment by nakayama-bird** [comment]
## 検索結果が表示できない
```ruby
  def search
    scope = Post.distinct
    scope = scope.address_contain(address_or_name).or(scope.name_contain(address_or_name)) if address_or_name.present?
    scope = scope.by_genre(genre_select) if genre_select.present?
    scope
    pp scope
  end
```
- フォームオブジェクトに`pp`挟んだら情報の取得はできてそう
```
 Post Load (0.5ms)  SELECT DISTINCT `posts`.* FROM `posts` WHERE `posts`.`genre` = 2 /* loading for pp */ LIMIT 11
web-1  | 23:13:05 web.1  |   ↳ app/forms/search_posts_form.rb:14:in `search'
web-1  | 23:13:05 web.1  | [#<Post:0x0000ffff96744758
web-1  | 23:13:05 web.1  |   id: 1,
web-1  | 23:13:05 web.1  |   restaurant_name: "タイトル0",
web-1  | 23:13:05 web.1  |   address: "住所0",
web-1  | 23:13:05 web.1  |   latitude: 50.0,
web-1  | 23:13:05 web.1  |   longitude: 50.0,
web-1  | 23:13:05 web.1  |   body: "本文0",
web-1  | 23:13:05 web.1  |   amount: nil,
web-1  | 23:13:05 web.1  |   user_id: 6,
web-1  | 23:13:05 web.1  |   created_at: Thu, 18 Jul 2024 17:12:57.282055000 JST +09:00,
web-1  | 23:13:05 web.1  |   updated_at: Thu, 18 Jul 2024 17:12:57.282055000 JST +09:00,
web-1  | 23:13:05 web.1  |   genre: "western_food",
web-1  | 23:13:05 web.1  |   post_images: nil,
web-1  | 23:13:05 web.1  |   rating: "very_poor">,
web-1  | 23:13:05 web.1  |  #<Post:0x0000ffff96744618
web-1  | 23:13:05 web.1  |   id: 13,
web-1  | 23:13:05 web.1  |   restaurant_name: "タイトル12",
web-1  | 23:13:05 web.1  |   address: "住所12",
web-1  | 23:13:05 web.1  |   latitude: 50.0,
web-1  | 23:13:05 web.1  |   longitude: 50.0,
web-1  | 23:13:05 web.1  |   body: "本文12",
web-1  | 23:13:05 web.1  |   amount: nil,
web-1  | 23:13:05 web.1  |   user_id: 3,
web-1  | 23:13:05 web.1  |   created_at: Thu, 18 Jul 2024 17:12:59.353904000 JST +09:00,
web-1  | 23:13:05 web.1  |   updated_at: Thu, 18 Jul 2024 17:12:59.353904000 JST +09:00,
web-1  | 23:13:05 web.1  |   genre: "western_food",
web-1  | 23:13:05 web.1  |   post_images: nil,
```

**Comment by nakayama-bird** [comment]
## コントローラの結果もちゃんとできてる
```ruby
  def search
    @posts = @search_form.search.includes(:user).order(created_at: :desc)
    pp @posts
  end
```
```
 Started GET "/maps/search?q%5Baddress_or_name%5D=&q%5Bgenre_select%5D=chinese_food&commit=%E6%A4%9C%E7%B4%A2" for 192.168.65.1 at 2024-08-23 23:31:51 +0900
web-1  | 23:31:51 web.1  | Cannot render console from 192.168.65.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web-1  | 23:31:51 web.1  | Processing by MapsController#search as HTML
web-1  | 23:31:51 web.1  |   Parameters: {"q"=>{"address_or_name"=>"", "genre_select"=>"chinese_food"}, "commit"=>"検索"}
web-1  | 23:31:51 web.1  |   Post Load (0.6ms)  SELECT DISTINCT `posts`.* FROM `posts` WHERE `posts`.`genre` = 1 /* loading for pp */ ORDER BY `posts`.`created_at` DESC LIMIT 11
web-1  | 23:31:51 web.1  |   ↳ app/controllers/maps_controller.rb:10:in `search'
web-1  | 23:31:51 web.1  |   User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` IN (11, 5)
web-1  | 23:31:51 web.1  |   ↳ app/controllers/maps_controller.rb:10:in `search'
web-1  | 23:31:51 web.1  | [#<Post:0x0000ffff96769da0
web-1  | 23:31:51 web.1  |   id: 44,
web-1  | 23:31:51 web.1  |   restaurant_name: "你好(ニイハオ) 渋谷店",
web-1  | 23:31:51 web.1  |   address: "日本、〒150-0002 東京都渋谷区渋谷２丁目１９−１７",
web-1  | 23:31:51 web.1  |   latitude: 35.6596,
web-1  | 23:31:51 web.1  |   longitude: 139.704,
web-1  | 23:31:51 web.1  |   body: "餃子",
web-1  | 23:31:51 web.1  |   amount: nil,
```

**Comment by nakayama-bird** [comment]
## リダイレクト
-検索した状態でリダイレクトすると検索結果が出てくる

**Comment by nakayama-bird** [comment]
## 解決方法
- 地図一覧表示、検索の際に`data: { turbo: false }`で無効化した
- [チュートリアル1 Railsで管理画面を作る｜猫でもわかるHotwire入門 Turbo編](https://zenn.dev/shita1112/books/cat-hotwire-turbo/viewer/tutorial-1)
- [Turbo Drive とは何か？](https://zenn.dev/takeyuwebinc/articles/8ebe80bf442dc2)
